/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.routines;


import com.corona.insights.jooq.corona_insights.CoronaInsights;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VincentyDistance extends AbstractRoutine<Double> {

    private static final long serialVersionUID = -2073190062;

    /**
     * The parameter <code>corona_insights.vincenty_distance.RETURN_VALUE</code>.
     */
    public static final Parameter<Double> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.DOUBLE, false, false);

    /**
     * The parameter <code>corona_insights.vincenty_distance.lat1</code>.
     */
    public static final Parameter<Double> LAT1 = Internal.createParameter("lat1", org.jooq.impl.SQLDataType.DOUBLE, false, false);

    /**
     * The parameter <code>corona_insights.vincenty_distance.lon1</code>.
     */
    public static final Parameter<Double> LON1 = Internal.createParameter("lon1", org.jooq.impl.SQLDataType.DOUBLE, false, false);

    /**
     * The parameter <code>corona_insights.vincenty_distance.lat2</code>.
     */
    public static final Parameter<Double> LAT2 = Internal.createParameter("lat2", org.jooq.impl.SQLDataType.DOUBLE, false, false);

    /**
     * The parameter <code>corona_insights.vincenty_distance.lon2</code>.
     */
    public static final Parameter<Double> LON2 = Internal.createParameter("lon2", org.jooq.impl.SQLDataType.DOUBLE, false, false);

    /**
     * Create a new routine call instance
     */
    public VincentyDistance() {
        super("vincenty_distance", CoronaInsights.CORONA_INSIGHTS, org.jooq.impl.SQLDataType.DOUBLE);

        setReturnParameter(RETURN_VALUE);
        addInParameter(LAT1);
        addInParameter(LON1);
        addInParameter(LAT2);
        addInParameter(LON2);
    }

    /**
     * Set the <code>lat1</code> parameter IN value to the routine
     */
    public void setLat1(Double value) {
        setValue(LAT1, value);
    }

    /**
     * Set the <code>lat1</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public VincentyDistance setLat1(Field<Double> field) {
        setField(LAT1, field);
        return this;
    }

    /**
     * Set the <code>lon1</code> parameter IN value to the routine
     */
    public void setLon1(Double value) {
        setValue(LON1, value);
    }

    /**
     * Set the <code>lon1</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public VincentyDistance setLon1(Field<Double> field) {
        setField(LON1, field);
        return this;
    }

    /**
     * Set the <code>lat2</code> parameter IN value to the routine
     */
    public void setLat2(Double value) {
        setValue(LAT2, value);
    }

    /**
     * Set the <code>lat2</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public VincentyDistance setLat2(Field<Double> field) {
        setField(LAT2, field);
        return this;
    }

    /**
     * Set the <code>lon2</code> parameter IN value to the routine
     */
    public void setLon2(Double value) {
        setValue(LON2, value);
    }

    /**
     * Set the <code>lon2</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public VincentyDistance setLon2(Field<Double> field) {
        setField(LON2, field);
        return this;
    }
}
