/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables;


import com.corona.insights.jooq.corona_insights.CoronaInsights;
import com.corona.insights.jooq.corona_insights.Indexes;
import com.corona.insights.jooq.corona_insights.Keys;
import com.corona.insights.jooq.corona_insights.tables.records.PropertiesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Properties extends TableImpl<PropertiesRecord> {

    private static final long serialVersionUID = -255316960;

    /**
     * The reference instance of <code>corona_insights.properties</code>
     */
    public static final Properties PROPERTIES = new Properties();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PropertiesRecord> getRecordType() {
        return PropertiesRecord.class;
    }

    /**
     * The column <code>corona_insights.properties.id</code>.
     */
    public final TableField<PropertiesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>corona_insights.properties.key</code>.
     */
    public final TableField<PropertiesRecord, String> KEY = createField("key", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>corona_insights.properties.value</code>.
     */
    public final TableField<PropertiesRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR(200).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>corona_insights.properties.modified_at</code>.
     */
    public final TableField<PropertiesRecord, Timestamp> MODIFIED_AT = createField("modified_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>corona_insights.properties</code> table reference
     */
    public Properties() {
        this(DSL.name("properties"), null);
    }

    /**
     * Create an aliased <code>corona_insights.properties</code> table reference
     */
    public Properties(String alias) {
        this(DSL.name(alias), PROPERTIES);
    }

    /**
     * Create an aliased <code>corona_insights.properties</code> table reference
     */
    public Properties(Name alias) {
        this(alias, PROPERTIES);
    }

    private Properties(Name alias, Table<PropertiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Properties(Name alias, Table<PropertiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Properties(Table<O> child, ForeignKey<O, PropertiesRecord> key) {
        super(child, key, PROPERTIES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CoronaInsights.CORONA_INSIGHTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PROPERTIES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PropertiesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_PROPERTIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PropertiesRecord> getPrimaryKey() {
        return Keys.KEY_PROPERTIES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PropertiesRecord>> getKeys() {
        return Arrays.<UniqueKey<PropertiesRecord>>asList(Keys.KEY_PROPERTIES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Properties as(String alias) {
        return new Properties(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Properties as(Name alias) {
        return new Properties(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Properties rename(String name) {
        return new Properties(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Properties rename(Name name) {
        return new Properties(name, null);
    }
}
