/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables;


import com.corona.insights.jooq.corona_insights.CoronaInsights;
import com.corona.insights.jooq.corona_insights.Indexes;
import com.corona.insights.jooq.corona_insights.Keys;
import com.corona.insights.jooq.corona_insights.tables.records.StateWiseRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StateWise extends TableImpl<StateWiseRecord> {

    private static final long serialVersionUID = 399386896;

    /**
     * The reference instance of <code>corona_insights.state_wise</code>
     */
    public static final StateWise STATE_WISE = new StateWise();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StateWiseRecord> getRecordType() {
        return StateWiseRecord.class;
    }

    /**
     * The column <code>corona_insights.state_wise.id</code>.
     */
    public final TableField<StateWiseRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>corona_insights.state_wise.reporting_date</code>.
     */
    public final TableField<StateWiseRecord, Date> REPORTING_DATE = createField("reporting_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>corona_insights.state_wise.country</code>.
     */
    public final TableField<StateWiseRecord, String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>corona_insights.state_wise.state</code>.
     */
    public final TableField<StateWiseRecord, String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR(11).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>corona_insights.state_wise.confirmed</code>.
     */
    public final TableField<StateWiseRecord, Long> CONFIRMED = createField("confirmed", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>corona_insights.state_wise.deaths</code>.
     */
    public final TableField<StateWiseRecord, Integer> DEATHS = createField("deaths", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>corona_insights.state_wise.recovered</code>.
     */
    public final TableField<StateWiseRecord, Long> RECOVERED = createField("recovered", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>corona_insights.state_wise.created_at</code>.
     */
    public final TableField<StateWiseRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>corona_insights.state_wise.modified_at</code>.
     */
    public final TableField<StateWiseRecord, Timestamp> MODIFIED_AT = createField("modified_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>corona_insights.state_wise</code> table reference
     */
    public StateWise() {
        this(DSL.name("state_wise"), null);
    }

    /**
     * Create an aliased <code>corona_insights.state_wise</code> table reference
     */
    public StateWise(String alias) {
        this(DSL.name(alias), STATE_WISE);
    }

    /**
     * Create an aliased <code>corona_insights.state_wise</code> table reference
     */
    public StateWise(Name alias) {
        this(alias, STATE_WISE);
    }

    private StateWise(Name alias, Table<StateWiseRecord> aliased) {
        this(alias, aliased, null);
    }

    private StateWise(Name alias, Table<StateWiseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> StateWise(Table<O> child, ForeignKey<O, StateWiseRecord> key) {
        super(child, key, STATE_WISE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CoronaInsights.CORONA_INSIGHTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STATE_WISE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StateWiseRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_STATE_WISE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StateWiseRecord> getPrimaryKey() {
        return Keys.KEY_STATE_WISE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StateWiseRecord>> getKeys() {
        return Arrays.<UniqueKey<StateWiseRecord>>asList(Keys.KEY_STATE_WISE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWise as(String alias) {
        return new StateWise(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWise as(Name alias) {
        return new StateWise(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StateWise rename(String name) {
        return new StateWise(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StateWise rename(Name name) {
        return new StateWise(name, null);
    }
}
