/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.records;


import com.corona.insights.jooq.corona_insights.tables.AgeWiseCases;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgeWiseCasesRecord extends UpdatableRecordImpl<AgeWiseCasesRecord> implements Record9<Integer, Integer, Integer, Timestamp, Long, ULong, ULong, Timestamp, Timestamp> {

    private static final long serialVersionUID = -186945932;

    /**
     * Setter for <code>corona_insights.age_wise_cases.id</code>.
     */
    public AgeWiseCasesRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.age_wise_cases.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>corona_insights.age_wise_cases.location_id</code>.
     */
    public AgeWiseCasesRecord setLocationId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.age_wise_cases.location_id</code>.
     */
    public Integer getLocationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>corona_insights.age_wise_cases.age</code>.
     */
    public AgeWiseCasesRecord setAge(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.age_wise_cases.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>corona_insights.age_wise_cases.reporting_date</code>.
     */
    public AgeWiseCasesRecord setReportingDate(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.age_wise_cases.reporting_date</code>.
     */
    public Timestamp getReportingDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>corona_insights.age_wise_cases.confirmed</code>.
     */
    public AgeWiseCasesRecord setConfirmed(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.age_wise_cases.confirmed</code>.
     */
    public Long getConfirmed() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>corona_insights.age_wise_cases.deaths</code>.
     */
    public AgeWiseCasesRecord setDeaths(ULong value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.age_wise_cases.deaths</code>.
     */
    public ULong getDeaths() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>corona_insights.age_wise_cases.recovered</code>.
     */
    public AgeWiseCasesRecord setRecovered(ULong value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.age_wise_cases.recovered</code>.
     */
    public ULong getRecovered() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>corona_insights.age_wise_cases.created_at</code>.
     */
    public AgeWiseCasesRecord setCreatedAt(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.age_wise_cases.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>corona_insights.age_wise_cases.modified_at</code>.
     */
    public AgeWiseCasesRecord setModifiedAt(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.age_wise_cases.modified_at</code>.
     */
    public Timestamp getModifiedAt() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Timestamp, Long, ULong, ULong, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Timestamp, Long, ULong, ULong, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AgeWiseCases.AGE_WISE_CASES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return AgeWiseCases.AGE_WISE_CASES.LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return AgeWiseCases.AGE_WISE_CASES.AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return AgeWiseCases.AGE_WISE_CASES.REPORTING_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return AgeWiseCases.AGE_WISE_CASES.CONFIRMED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field6() {
        return AgeWiseCases.AGE_WISE_CASES.DEATHS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field7() {
        return AgeWiseCases.AGE_WISE_CASES.RECOVERED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return AgeWiseCases.AGE_WISE_CASES.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return AgeWiseCases.AGE_WISE_CASES.MODIFIED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getReportingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component6() {
        return getDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component7() {
        return getRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getReportingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value6() {
        return getDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value7() {
        return getRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgeWiseCasesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgeWiseCasesRecord value2(Integer value) {
        setLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgeWiseCasesRecord value3(Integer value) {
        setAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgeWiseCasesRecord value4(Timestamp value) {
        setReportingDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgeWiseCasesRecord value5(Long value) {
        setConfirmed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgeWiseCasesRecord value6(ULong value) {
        setDeaths(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgeWiseCasesRecord value7(ULong value) {
        setRecovered(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgeWiseCasesRecord value8(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgeWiseCasesRecord value9(Timestamp value) {
        setModifiedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgeWiseCasesRecord values(Integer value1, Integer value2, Integer value3, Timestamp value4, Long value5, ULong value6, ULong value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgeWiseCasesRecord
     */
    public AgeWiseCasesRecord() {
        super(AgeWiseCases.AGE_WISE_CASES);
    }

    /**
     * Create a detached, initialised AgeWiseCasesRecord
     */
    public AgeWiseCasesRecord(Integer id, Integer locationId, Integer age, Timestamp reportingDate, Long confirmed, ULong deaths, ULong recovered, Timestamp createdAt, Timestamp modifiedAt) {
        super(AgeWiseCases.AGE_WISE_CASES);

        set(0, id);
        set(1, locationId);
        set(2, age);
        set(3, reportingDate);
        set(4, confirmed);
        set(5, deaths);
        set(6, recovered);
        set(7, createdAt);
        set(8, modifiedAt);
    }
}
