/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.records;


import com.corona.insights.jooq.corona_insights.tables.Cases;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CasesRecord extends UpdatableRecordImpl<CasesRecord> implements Record10<Integer, Integer, Date, Long, Integer, Long, Timestamp, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1175485183;

    /**
     * Setter for <code>corona_insights.cases.id</code>.
     */
    public CasesRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.cases.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>corona_insights.cases.location_id</code>.
     */
    public CasesRecord setLocationId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.cases.location_id</code>.
     */
    public Integer getLocationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>corona_insights.cases.reporting_date</code>.
     */
    public CasesRecord setReportingDate(Date value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.cases.reporting_date</code>.
     */
    public Date getReportingDate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>corona_insights.cases.confirmed</code>.
     */
    public CasesRecord setConfirmed(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.cases.confirmed</code>.
     */
    public Long getConfirmed() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>corona_insights.cases.deaths</code>.
     */
    public CasesRecord setDeaths(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.cases.deaths</code>.
     */
    public Integer getDeaths() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>corona_insights.cases.recovered</code>.
     */
    public CasesRecord setRecovered(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.cases.recovered</code>.
     */
    public Long getRecovered() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>corona_insights.cases.reporting_timestamp</code>.
     */
    public CasesRecord setReportingTimestamp(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.cases.reporting_timestamp</code>.
     */
    public Timestamp getReportingTimestamp() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>corona_insights.cases.file_name</code>.
     */
    public CasesRecord setFileName(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.cases.file_name</code>.
     */
    public String getFileName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>corona_insights.cases.created_At</code>.
     */
    public CasesRecord setCreatedAt(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.cases.created_At</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>corona_insights.cases.modified_at</code>.
     */
    public CasesRecord setModifiedAt(Timestamp value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.cases.modified_at</code>.
     */
    public Timestamp getModifiedAt() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Date, Long, Integer, Long, Timestamp, String, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Date, Long, Integer, Long, Timestamp, String, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Cases.CASES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Cases.CASES.LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Cases.CASES.REPORTING_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Cases.CASES.CONFIRMED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Cases.CASES.DEATHS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Cases.CASES.RECOVERED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Cases.CASES.REPORTING_TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Cases.CASES.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Cases.CASES.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Cases.CASES.MODIFIED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component3() {
        return getReportingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getReportingTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getReportingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getReportingTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasesRecord value2(Integer value) {
        setLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasesRecord value3(Date value) {
        setReportingDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasesRecord value4(Long value) {
        setConfirmed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasesRecord value5(Integer value) {
        setDeaths(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasesRecord value6(Long value) {
        setRecovered(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasesRecord value7(Timestamp value) {
        setReportingTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasesRecord value8(String value) {
        setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasesRecord value9(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasesRecord value10(Timestamp value) {
        setModifiedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasesRecord values(Integer value1, Integer value2, Date value3, Long value4, Integer value5, Long value6, Timestamp value7, String value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CasesRecord
     */
    public CasesRecord() {
        super(Cases.CASES);
    }

    /**
     * Create a detached, initialised CasesRecord
     */
    public CasesRecord(Integer id, Integer locationId, Date reportingDate, Long confirmed, Integer deaths, Long recovered, Timestamp reportingTimestamp, String fileName, Timestamp createdAt, Timestamp modifiedAt) {
        super(Cases.CASES);

        set(0, id);
        set(1, locationId);
        set(2, reportingDate);
        set(3, confirmed);
        set(4, deaths);
        set(5, recovered);
        set(6, reportingTimestamp);
        set(7, fileName);
        set(8, createdAt);
        set(9, modifiedAt);
    }
}
