/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.records;


import com.corona.insights.jooq.corona_insights.enums.CountryWiseSource;
import com.corona.insights.jooq.corona_insights.tables.CountryWise;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CountryWiseRecord extends UpdatableRecordImpl<CountryWiseRecord> implements Record9<Integer, Date, String, Long, Integer, Long, CountryWiseSource, Timestamp, Timestamp> {

    private static final long serialVersionUID = 652480815;

    /**
     * Setter for <code>corona_insights.country_wise.id</code>.
     */
    public CountryWiseRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.country_wise.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>corona_insights.country_wise.reporting_date</code>.
     */
    public CountryWiseRecord setReportingDate(Date value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.country_wise.reporting_date</code>.
     */
    public Date getReportingDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>corona_insights.country_wise.country</code>.
     */
    public CountryWiseRecord setCountry(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.country_wise.country</code>.
     */
    public String getCountry() {
        return (String) get(2);
    }

    /**
     * Setter for <code>corona_insights.country_wise.confirmed</code>.
     */
    public CountryWiseRecord setConfirmed(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.country_wise.confirmed</code>.
     */
    public Long getConfirmed() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>corona_insights.country_wise.deaths</code>.
     */
    public CountryWiseRecord setDeaths(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.country_wise.deaths</code>.
     */
    public Integer getDeaths() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>corona_insights.country_wise.recovered</code>.
     */
    public CountryWiseRecord setRecovered(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.country_wise.recovered</code>.
     */
    public Long getRecovered() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>corona_insights.country_wise.source</code>.
     */
    public CountryWiseRecord setSource(CountryWiseSource value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.country_wise.source</code>.
     */
    public CountryWiseSource getSource() {
        return (CountryWiseSource) get(6);
    }

    /**
     * Setter for <code>corona_insights.country_wise.created_at</code>.
     */
    public CountryWiseRecord setCreatedAt(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.country_wise.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>corona_insights.country_wise.modified_at</code>.
     */
    public CountryWiseRecord setModifiedAt(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.country_wise.modified_at</code>.
     */
    public Timestamp getModifiedAt() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Date, String, Long, Integer, Long, CountryWiseSource, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Date, String, Long, Integer, Long, CountryWiseSource, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CountryWise.COUNTRY_WISE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return CountryWise.COUNTRY_WISE.REPORTING_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CountryWise.COUNTRY_WISE.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return CountryWise.COUNTRY_WISE.CONFIRMED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return CountryWise.COUNTRY_WISE.DEATHS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return CountryWise.COUNTRY_WISE.RECOVERED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<CountryWiseSource> field7() {
        return CountryWise.COUNTRY_WISE.SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return CountryWise.COUNTRY_WISE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return CountryWise.COUNTRY_WISE.MODIFIED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getReportingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountryWiseSource component7() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getReportingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountryWiseSource value7() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountryWiseRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountryWiseRecord value2(Date value) {
        setReportingDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountryWiseRecord value3(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountryWiseRecord value4(Long value) {
        setConfirmed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountryWiseRecord value5(Integer value) {
        setDeaths(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountryWiseRecord value6(Long value) {
        setRecovered(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountryWiseRecord value7(CountryWiseSource value) {
        setSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountryWiseRecord value8(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountryWiseRecord value9(Timestamp value) {
        setModifiedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CountryWiseRecord values(Integer value1, Date value2, String value3, Long value4, Integer value5, Long value6, CountryWiseSource value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CountryWiseRecord
     */
    public CountryWiseRecord() {
        super(CountryWise.COUNTRY_WISE);
    }

    /**
     * Create a detached, initialised CountryWiseRecord
     */
    public CountryWiseRecord(Integer id, Date reportingDate, String country, Long confirmed, Integer deaths, Long recovered, CountryWiseSource source, Timestamp createdAt, Timestamp modifiedAt) {
        super(CountryWise.COUNTRY_WISE);

        set(0, id);
        set(1, reportingDate);
        set(2, country);
        set(3, confirmed);
        set(4, deaths);
        set(5, recovered);
        set(6, source);
        set(7, createdAt);
        set(8, modifiedAt);
    }
}
