/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.records;


import com.corona.insights.jooq.corona_insights.enums.DistrictWiseSource;
import com.corona.insights.jooq.corona_insights.tables.DistrictWise;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DistrictWiseRecord extends UpdatableRecordImpl<DistrictWiseRecord> implements Record18<UInteger, Date, String, String, String, Integer, Integer, Integer, Long, Integer, Long, Long, Integer, BigDecimal, BigDecimal, DistrictWiseSource, Timestamp, Timestamp> {

    private static final long serialVersionUID = -77803375;

    /**
     * Setter for <code>corona_insights.district_wise.id</code>.
     */
    public DistrictWiseRecord setId(UInteger value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>corona_insights.district_wise.reporting_date</code>.
     */
    public DistrictWiseRecord setReportingDate(Date value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.reporting_date</code>.
     */
    public Date getReportingDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>corona_insights.district_wise.country</code>.
     */
    public DistrictWiseRecord setCountry(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.country</code>.
     */
    public String getCountry() {
        return (String) get(2);
    }

    /**
     * Setter for <code>corona_insights.district_wise.state</code>.
     */
    public DistrictWiseRecord setState(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.state</code>.
     */
    public String getState() {
        return (String) get(3);
    }

    /**
     * Setter for <code>corona_insights.district_wise.district</code>.
     */
    public DistrictWiseRecord setDistrict(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.district</code>.
     */
    public String getDistrict() {
        return (String) get(4);
    }

    /**
     * Setter for <code>corona_insights.district_wise.delta_confirmed</code>.
     */
    public DistrictWiseRecord setDeltaConfirmed(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.delta_confirmed</code>.
     */
    public Integer getDeltaConfirmed() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>corona_insights.district_wise.delta_deaths</code>.
     */
    public DistrictWiseRecord setDeltaDeaths(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.delta_deaths</code>.
     */
    public Integer getDeltaDeaths() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>corona_insights.district_wise.delta_recovered</code>.
     */
    public DistrictWiseRecord setDeltaRecovered(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.delta_recovered</code>.
     */
    public Integer getDeltaRecovered() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>corona_insights.district_wise.confirmed</code>.
     */
    public DistrictWiseRecord setConfirmed(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.confirmed</code>.
     */
    public Long getConfirmed() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>corona_insights.district_wise.deaths</code>.
     */
    public DistrictWiseRecord setDeaths(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.deaths</code>.
     */
    public Integer getDeaths() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>corona_insights.district_wise.recovered</code>.
     */
    public DistrictWiseRecord setRecovered(Long value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.recovered</code>.
     */
    public Long getRecovered() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>corona_insights.district_wise.active</code>.
     */
    public DistrictWiseRecord setActive(Long value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.active</code>.
     */
    public Long getActive() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>corona_insights.district_wise.delta_active</code>.
     */
    public DistrictWiseRecord setDeltaActive(Integer value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.delta_active</code>.
     */
    public Integer getDeltaActive() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>corona_insights.district_wise.latitude</code>.
     */
    public DistrictWiseRecord setLatitude(BigDecimal value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>corona_insights.district_wise.longitude</code>.
     */
    public DistrictWiseRecord setLongitude(BigDecimal value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>corona_insights.district_wise.source</code>.
     */
    public DistrictWiseRecord setSource(DistrictWiseSource value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.source</code>.
     */
    public DistrictWiseSource getSource() {
        return (DistrictWiseSource) get(15);
    }

    /**
     * Setter for <code>corona_insights.district_wise.created_at</code>.
     */
    public DistrictWiseRecord setCreatedAt(Timestamp value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(16);
    }

    /**
     * Setter for <code>corona_insights.district_wise.modified_at</code>.
     */
    public DistrictWiseRecord setModifiedAt(Timestamp value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.modified_at</code>.
     */
    public Timestamp getModifiedAt() {
        return (Timestamp) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<UInteger, Date, String, String, String, Integer, Integer, Integer, Long, Integer, Long, Long, Integer, BigDecimal, BigDecimal, DistrictWiseSource, Timestamp, Timestamp> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<UInteger, Date, String, String, String, Integer, Integer, Integer, Long, Integer, Long, Long, Integer, BigDecimal, BigDecimal, DistrictWiseSource, Timestamp, Timestamp> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return DistrictWise.DISTRICT_WISE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return DistrictWise.DISTRICT_WISE.REPORTING_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DistrictWise.DISTRICT_WISE.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DistrictWise.DISTRICT_WISE.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DistrictWise.DISTRICT_WISE.DISTRICT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return DistrictWise.DISTRICT_WISE.DELTA_CONFIRMED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return DistrictWise.DISTRICT_WISE.DELTA_DEATHS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return DistrictWise.DISTRICT_WISE.DELTA_RECOVERED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return DistrictWise.DISTRICT_WISE.CONFIRMED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return DistrictWise.DISTRICT_WISE.DEATHS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return DistrictWise.DISTRICT_WISE.RECOVERED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return DistrictWise.DISTRICT_WISE.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return DistrictWise.DISTRICT_WISE.DELTA_ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field14() {
        return DistrictWise.DISTRICT_WISE.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field15() {
        return DistrictWise.DISTRICT_WISE.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<DistrictWiseSource> field16() {
        return DistrictWise.DISTRICT_WISE.SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field17() {
        return DistrictWise.DISTRICT_WISE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return DistrictWise.DISTRICT_WISE.MODIFIED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getReportingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getDeltaConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getDeltaDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getDeltaRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component11() {
        return getRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getDeltaActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component14() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component15() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseSource component16() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component17() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component18() {
        return getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getReportingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getDeltaConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getDeltaDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getDeltaRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getDeltaActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value14() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value15() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseSource value16() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value17() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value2(Date value) {
        setReportingDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value3(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value4(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value5(String value) {
        setDistrict(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value6(Integer value) {
        setDeltaConfirmed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value7(Integer value) {
        setDeltaDeaths(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value8(Integer value) {
        setDeltaRecovered(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value9(Long value) {
        setConfirmed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value10(Integer value) {
        setDeaths(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value11(Long value) {
        setRecovered(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value12(Long value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value13(Integer value) {
        setDeltaActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value14(BigDecimal value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value15(BigDecimal value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value16(DistrictWiseSource value) {
        setSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value17(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value18(Timestamp value) {
        setModifiedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord values(UInteger value1, Date value2, String value3, String value4, String value5, Integer value6, Integer value7, Integer value8, Long value9, Integer value10, Long value11, Long value12, Integer value13, BigDecimal value14, BigDecimal value15, DistrictWiseSource value16, Timestamp value17, Timestamp value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DistrictWiseRecord
     */
    public DistrictWiseRecord() {
        super(DistrictWise.DISTRICT_WISE);
    }

    /**
     * Create a detached, initialised DistrictWiseRecord
     */
    public DistrictWiseRecord(UInteger id, Date reportingDate, String country, String state, String district, Integer deltaConfirmed, Integer deltaDeaths, Integer deltaRecovered, Long confirmed, Integer deaths, Long recovered, Long active, Integer deltaActive, BigDecimal latitude, BigDecimal longitude, DistrictWiseSource source, Timestamp createdAt, Timestamp modifiedAt) {
        super(DistrictWise.DISTRICT_WISE);

        set(0, id);
        set(1, reportingDate);
        set(2, country);
        set(3, state);
        set(4, district);
        set(5, deltaConfirmed);
        set(6, deltaDeaths);
        set(7, deltaRecovered);
        set(8, confirmed);
        set(9, deaths);
        set(10, recovered);
        set(11, active);
        set(12, deltaActive);
        set(13, latitude);
        set(14, longitude);
        set(15, source);
        set(16, createdAt);
        set(17, modifiedAt);
    }
}
