/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.records;


import com.corona.insights.jooq.corona_insights.tables.DistrictWise;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DistrictWiseRecord extends UpdatableRecordImpl<DistrictWiseRecord> implements Record12<UInteger, Date, String, String, String, Long, Integer, Long, BigDecimal, BigDecimal, Timestamp, Timestamp> {

    private static final long serialVersionUID = 2112241821;

    /**
     * Setter for <code>corona_insights.district_wise.id</code>.
     */
    public DistrictWiseRecord setId(UInteger value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>corona_insights.district_wise.reporting_date</code>.
     */
    public DistrictWiseRecord setReportingDate(Date value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.reporting_date</code>.
     */
    public Date getReportingDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>corona_insights.district_wise.country</code>.
     */
    public DistrictWiseRecord setCountry(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.country</code>.
     */
    public String getCountry() {
        return (String) get(2);
    }

    /**
     * Setter for <code>corona_insights.district_wise.state</code>.
     */
    public DistrictWiseRecord setState(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.state</code>.
     */
    public String getState() {
        return (String) get(3);
    }

    /**
     * Setter for <code>corona_insights.district_wise.district</code>.
     */
    public DistrictWiseRecord setDistrict(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.district</code>.
     */
    public String getDistrict() {
        return (String) get(4);
    }

    /**
     * Setter for <code>corona_insights.district_wise.confirmed</code>.
     */
    public DistrictWiseRecord setConfirmed(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.confirmed</code>.
     */
    public Long getConfirmed() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>corona_insights.district_wise.deaths</code>.
     */
    public DistrictWiseRecord setDeaths(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.deaths</code>.
     */
    public Integer getDeaths() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>corona_insights.district_wise.recovered</code>.
     */
    public DistrictWiseRecord setRecovered(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.recovered</code>.
     */
    public Long getRecovered() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>corona_insights.district_wise.latitude</code>.
     */
    public DistrictWiseRecord setLatitude(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>corona_insights.district_wise.longitude</code>.
     */
    public DistrictWiseRecord setLongitude(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>corona_insights.district_wise.created_at</code>.
     */
    public DistrictWiseRecord setCreatedAt(Timestamp value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>corona_insights.district_wise.modified_at</code>.
     */
    public DistrictWiseRecord setModifiedAt(Timestamp value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.district_wise.modified_at</code>.
     */
    public Timestamp getModifiedAt() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<UInteger, Date, String, String, String, Long, Integer, Long, BigDecimal, BigDecimal, Timestamp, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<UInteger, Date, String, String, String, Long, Integer, Long, BigDecimal, BigDecimal, Timestamp, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return DistrictWise.DISTRICT_WISE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return DistrictWise.DISTRICT_WISE.REPORTING_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DistrictWise.DISTRICT_WISE.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DistrictWise.DISTRICT_WISE.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DistrictWise.DISTRICT_WISE.DISTRICT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return DistrictWise.DISTRICT_WISE.CONFIRMED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return DistrictWise.DISTRICT_WISE.DEATHS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return DistrictWise.DISTRICT_WISE.RECOVERED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return DistrictWise.DISTRICT_WISE.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return DistrictWise.DISTRICT_WISE.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return DistrictWise.DISTRICT_WISE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return DistrictWise.DISTRICT_WISE.MODIFIED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getReportingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component9() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component10() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getReportingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value2(Date value) {
        setReportingDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value3(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value4(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value5(String value) {
        setDistrict(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value6(Long value) {
        setConfirmed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value7(Integer value) {
        setDeaths(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value8(Long value) {
        setRecovered(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value9(BigDecimal value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value10(BigDecimal value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value11(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord value12(Timestamp value) {
        setModifiedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistrictWiseRecord values(UInteger value1, Date value2, String value3, String value4, String value5, Long value6, Integer value7, Long value8, BigDecimal value9, BigDecimal value10, Timestamp value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DistrictWiseRecord
     */
    public DistrictWiseRecord() {
        super(DistrictWise.DISTRICT_WISE);
    }

    /**
     * Create a detached, initialised DistrictWiseRecord
     */
    public DistrictWiseRecord(UInteger id, Date reportingDate, String country, String state, String district, Long confirmed, Integer deaths, Long recovered, BigDecimal latitude, BigDecimal longitude, Timestamp createdAt, Timestamp modifiedAt) {
        super(DistrictWise.DISTRICT_WISE);

        set(0, id);
        set(1, reportingDate);
        set(2, country);
        set(3, state);
        set(4, district);
        set(5, confirmed);
        set(6, deaths);
        set(7, recovered);
        set(8, latitude);
        set(9, longitude);
        set(10, createdAt);
        set(11, modifiedAt);
    }
}
