/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.records;


import com.corona.insights.jooq.corona_insights.tables.Properties;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PropertiesRecord extends UpdatableRecordImpl<PropertiesRecord> implements Record4<UInteger, String, String, Timestamp> {

    private static final long serialVersionUID = 2081847910;

    /**
     * Setter for <code>corona_insights.properties.id</code>.
     */
    public PropertiesRecord setId(UInteger value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.properties.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>corona_insights.properties.key</code>.
     */
    public PropertiesRecord setKey(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.properties.key</code>.
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>corona_insights.properties.value</code>.
     */
    public PropertiesRecord setValue(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.properties.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>corona_insights.properties.value_modified_at</code>.
     */
    public PropertiesRecord setValueModifiedAt(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.properties.value_modified_at</code>.
     */
    public Timestamp getValueModifiedAt() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, String, String, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, String, String, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Properties.PROPERTIES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Properties.PROPERTIES.KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Properties.PROPERTIES.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Properties.PROPERTIES.VALUE_MODIFIED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getValueModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getValueModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertiesRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertiesRecord value2(String value) {
        setKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertiesRecord value3(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertiesRecord value4(Timestamp value) {
        setValueModifiedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertiesRecord values(UInteger value1, String value2, String value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PropertiesRecord
     */
    public PropertiesRecord() {
        super(Properties.PROPERTIES);
    }

    /**
     * Create a detached, initialised PropertiesRecord
     */
    public PropertiesRecord(UInteger id, String key, String value, Timestamp valueModifiedAt) {
        super(Properties.PROPERTIES);

        set(0, id);
        set(1, key);
        set(2, value);
        set(3, valueModifiedAt);
    }
}
