/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.records;


import com.corona.insights.jooq.corona_insights.enums.StateWiseSource;
import com.corona.insights.jooq.corona_insights.tables.StateWise;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StateWiseRecord extends UpdatableRecordImpl<StateWiseRecord> implements Record15<UInteger, Date, String, String, Integer, Integer, Integer, Long, Integer, Long, Long, Integer, StateWiseSource, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1592016305;

    /**
     * Setter for <code>corona_insights.state_wise.id</code>.
     */
    public StateWiseRecord setId(UInteger value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>corona_insights.state_wise.reporting_date</code>.
     */
    public StateWiseRecord setReportingDate(Date value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.reporting_date</code>.
     */
    public Date getReportingDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>corona_insights.state_wise.country</code>.
     */
    public StateWiseRecord setCountry(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.country</code>.
     */
    public String getCountry() {
        return (String) get(2);
    }

    /**
     * Setter for <code>corona_insights.state_wise.state</code>.
     */
    public StateWiseRecord setState(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.state</code>.
     */
    public String getState() {
        return (String) get(3);
    }

    /**
     * Setter for <code>corona_insights.state_wise.delta_confirmed</code>.
     */
    public StateWiseRecord setDeltaConfirmed(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.delta_confirmed</code>.
     */
    public Integer getDeltaConfirmed() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>corona_insights.state_wise.delta_deaths</code>.
     */
    public StateWiseRecord setDeltaDeaths(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.delta_deaths</code>.
     */
    public Integer getDeltaDeaths() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>corona_insights.state_wise.delta_recovered</code>.
     */
    public StateWiseRecord setDeltaRecovered(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.delta_recovered</code>.
     */
    public Integer getDeltaRecovered() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>corona_insights.state_wise.confirmed</code>.
     */
    public StateWiseRecord setConfirmed(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.confirmed</code>.
     */
    public Long getConfirmed() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>corona_insights.state_wise.deaths</code>.
     */
    public StateWiseRecord setDeaths(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.deaths</code>.
     */
    public Integer getDeaths() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>corona_insights.state_wise.recovered</code>.
     */
    public StateWiseRecord setRecovered(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.recovered</code>.
     */
    public Long getRecovered() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>corona_insights.state_wise.active</code>.
     */
    public StateWiseRecord setActive(Long value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.active</code>.
     */
    public Long getActive() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>corona_insights.state_wise.delta_active</code>.
     */
    public StateWiseRecord setDeltaActive(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.delta_active</code>.
     */
    public Integer getDeltaActive() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>corona_insights.state_wise.source</code>.
     */
    public StateWiseRecord setSource(StateWiseSource value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.source</code>.
     */
    public StateWiseSource getSource() {
        return (StateWiseSource) get(12);
    }

    /**
     * Setter for <code>corona_insights.state_wise.created_at</code>.
     */
    public StateWiseRecord setCreatedAt(Timestamp value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>corona_insights.state_wise.modified_at</code>.
     */
    public StateWiseRecord setModifiedAt(Timestamp value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.modified_at</code>.
     */
    public Timestamp getModifiedAt() {
        return (Timestamp) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<UInteger, Date, String, String, Integer, Integer, Integer, Long, Integer, Long, Long, Integer, StateWiseSource, Timestamp, Timestamp> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<UInteger, Date, String, String, Integer, Integer, Integer, Long, Integer, Long, Long, Integer, StateWiseSource, Timestamp, Timestamp> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return StateWise.STATE_WISE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return StateWise.STATE_WISE.REPORTING_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return StateWise.STATE_WISE.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return StateWise.STATE_WISE.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return StateWise.STATE_WISE.DELTA_CONFIRMED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return StateWise.STATE_WISE.DELTA_DEATHS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return StateWise.STATE_WISE.DELTA_RECOVERED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return StateWise.STATE_WISE.CONFIRMED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return StateWise.STATE_WISE.DEATHS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return StateWise.STATE_WISE.RECOVERED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return StateWise.STATE_WISE.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return StateWise.STATE_WISE.DELTA_ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<StateWiseSource> field13() {
        return StateWise.STATE_WISE.SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return StateWise.STATE_WISE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return StateWise.STATE_WISE.MODIFIED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getReportingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getDeltaConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getDeltaDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getDeltaRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component11() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getDeltaActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseSource component13() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component15() {
        return getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getReportingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getDeltaConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getDeltaDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getDeltaRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getDeltaActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseSource value13() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value2(Date value) {
        setReportingDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value3(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value4(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value5(Integer value) {
        setDeltaConfirmed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value6(Integer value) {
        setDeltaDeaths(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value7(Integer value) {
        setDeltaRecovered(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value8(Long value) {
        setConfirmed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value9(Integer value) {
        setDeaths(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value10(Long value) {
        setRecovered(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value11(Long value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value12(Integer value) {
        setDeltaActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value13(StateWiseSource value) {
        setSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value14(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value15(Timestamp value) {
        setModifiedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord values(UInteger value1, Date value2, String value3, String value4, Integer value5, Integer value6, Integer value7, Long value8, Integer value9, Long value10, Long value11, Integer value12, StateWiseSource value13, Timestamp value14, Timestamp value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StateWiseRecord
     */
    public StateWiseRecord() {
        super(StateWise.STATE_WISE);
    }

    /**
     * Create a detached, initialised StateWiseRecord
     */
    public StateWiseRecord(UInteger id, Date reportingDate, String country, String state, Integer deltaConfirmed, Integer deltaDeaths, Integer deltaRecovered, Long confirmed, Integer deaths, Long recovered, Long active, Integer deltaActive, StateWiseSource source, Timestamp createdAt, Timestamp modifiedAt) {
        super(StateWise.STATE_WISE);

        set(0, id);
        set(1, reportingDate);
        set(2, country);
        set(3, state);
        set(4, deltaConfirmed);
        set(5, deltaDeaths);
        set(6, deltaRecovered);
        set(7, confirmed);
        set(8, deaths);
        set(9, recovered);
        set(10, active);
        set(11, deltaActive);
        set(12, source);
        set(13, createdAt);
        set(14, modifiedAt);
    }
}
