/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.records;


import com.corona.insights.jooq.corona_insights.tables.StateWise;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StateWiseRecord extends UpdatableRecordImpl<StateWiseRecord> implements Record9<UInteger, Date, String, String, Long, Integer, Long, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1735838603;

    /**
     * Setter for <code>corona_insights.state_wise.id</code>.
     */
    public StateWiseRecord setId(UInteger value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>corona_insights.state_wise.reporting_date</code>.
     */
    public StateWiseRecord setReportingDate(Date value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.reporting_date</code>.
     */
    public Date getReportingDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>corona_insights.state_wise.country</code>.
     */
    public StateWiseRecord setCountry(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.country</code>.
     */
    public String getCountry() {
        return (String) get(2);
    }

    /**
     * Setter for <code>corona_insights.state_wise.state</code>.
     */
    public StateWiseRecord setState(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.state</code>.
     */
    public String getState() {
        return (String) get(3);
    }

    /**
     * Setter for <code>corona_insights.state_wise.confirmed</code>.
     */
    public StateWiseRecord setConfirmed(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.confirmed</code>.
     */
    public Long getConfirmed() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>corona_insights.state_wise.deaths</code>.
     */
    public StateWiseRecord setDeaths(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.deaths</code>.
     */
    public Integer getDeaths() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>corona_insights.state_wise.recovered</code>.
     */
    public StateWiseRecord setRecovered(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.recovered</code>.
     */
    public Long getRecovered() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>corona_insights.state_wise.created_at</code>.
     */
    public StateWiseRecord setCreatedAt(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>corona_insights.state_wise.modified_at</code>.
     */
    public StateWiseRecord setModifiedAt(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>corona_insights.state_wise.modified_at</code>.
     */
    public Timestamp getModifiedAt() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UInteger, Date, String, String, Long, Integer, Long, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UInteger, Date, String, String, Long, Integer, Long, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return StateWise.STATE_WISE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return StateWise.STATE_WISE.REPORTING_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return StateWise.STATE_WISE.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return StateWise.STATE_WISE.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return StateWise.STATE_WISE.CONFIRMED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return StateWise.STATE_WISE.DEATHS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return StateWise.STATE_WISE.RECOVERED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return StateWise.STATE_WISE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return StateWise.STATE_WISE.MODIFIED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getReportingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getReportingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getDeaths();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getRecovered();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value2(Date value) {
        setReportingDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value3(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value4(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value5(Long value) {
        setConfirmed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value6(Integer value) {
        setDeaths(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value7(Long value) {
        setRecovered(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value8(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord value9(Timestamp value) {
        setModifiedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StateWiseRecord values(UInteger value1, Date value2, String value3, String value4, Long value5, Integer value6, Long value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StateWiseRecord
     */
    public StateWiseRecord() {
        super(StateWise.STATE_WISE);
    }

    /**
     * Create a detached, initialised StateWiseRecord
     */
    public StateWiseRecord(UInteger id, Date reportingDate, String country, String state, Long confirmed, Integer deaths, Long recovered, Timestamp createdAt, Timestamp modifiedAt) {
        super(StateWise.STATE_WISE);

        set(0, id);
        set(1, reportingDate);
        set(2, country);
        set(3, state);
        set(4, confirmed);
        set(5, deaths);
        set(6, recovered);
        set(7, createdAt);
        set(8, modifiedAt);
    }
}
