/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights;


import com.corona.insights.jooq.corona_insights.routines.VincentyDistance;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in corona_insights
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>corona_insights.vincenty_distance</code>
     */
    public static Double vincentyDistance(Configuration configuration, Double lat1, Double lon1, Double lat2, Double lon2) {
        VincentyDistance f = new VincentyDistance();
        f.setLat1(lat1);
        f.setLon1(lon1);
        f.setLat2(lat2);
        f.setLon2(lon2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>corona_insights.vincenty_distance</code> as a field.
     */
    public static Field<Double> vincentyDistance(Double lat1, Double lon1, Double lat2, Double lon2) {
        VincentyDistance f = new VincentyDistance();
        f.setLat1(lat1);
        f.setLon1(lon1);
        f.setLat2(lat2);
        f.setLon2(lon2);

        return f.asField();
    }

    /**
     * Get <code>corona_insights.vincenty_distance</code> as a field.
     */
    public static Field<Double> vincentyDistance(Field<Double> lat1, Field<Double> lon1, Field<Double> lat2, Field<Double> lon2) {
        VincentyDistance f = new VincentyDistance();
        f.setLat1(lat1);
        f.setLon1(lon1);
        f.setLat2(lat2);
        f.setLon2(lon2);

        return f.asField();
    }
}
