/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgeWiseCases implements Serializable {

    private static final long serialVersionUID = -895474932;

    private UInteger  id;
    private Integer   locationId;
    private Integer   age;
    private Timestamp reportingDate;
    private Long      confirmed;
    private ULong     deaths;
    private ULong     recovered;
    private Timestamp createdAt;
    private Timestamp modifiedAt;

    public AgeWiseCases() {}

    public AgeWiseCases(AgeWiseCases value) {
        this.id = value.id;
        this.locationId = value.locationId;
        this.age = value.age;
        this.reportingDate = value.reportingDate;
        this.confirmed = value.confirmed;
        this.deaths = value.deaths;
        this.recovered = value.recovered;
        this.createdAt = value.createdAt;
        this.modifiedAt = value.modifiedAt;
    }

    public AgeWiseCases(
        UInteger  id,
        Integer   locationId,
        Integer   age,
        Timestamp reportingDate,
        Long      confirmed,
        ULong     deaths,
        ULong     recovered,
        Timestamp createdAt,
        Timestamp modifiedAt
    ) {
        this.id = id;
        this.locationId = locationId;
        this.age = age;
        this.reportingDate = reportingDate;
        this.confirmed = confirmed;
        this.deaths = deaths;
        this.recovered = recovered;
        this.createdAt = createdAt;
        this.modifiedAt = modifiedAt;
    }

    public UInteger getId() {
        return this.id;
    }

    public AgeWiseCases setId(UInteger id) {
        this.id = id;
        return this;
    }

    public Integer getLocationId() {
        return this.locationId;
    }

    public AgeWiseCases setLocationId(Integer locationId) {
        this.locationId = locationId;
        return this;
    }

    public Integer getAge() {
        return this.age;
    }

    public AgeWiseCases setAge(Integer age) {
        this.age = age;
        return this;
    }

    public Timestamp getReportingDate() {
        return this.reportingDate;
    }

    public AgeWiseCases setReportingDate(Timestamp reportingDate) {
        this.reportingDate = reportingDate;
        return this;
    }

    public Long getConfirmed() {
        return this.confirmed;
    }

    public AgeWiseCases setConfirmed(Long confirmed) {
        this.confirmed = confirmed;
        return this;
    }

    public ULong getDeaths() {
        return this.deaths;
    }

    public AgeWiseCases setDeaths(ULong deaths) {
        this.deaths = deaths;
        return this;
    }

    public ULong getRecovered() {
        return this.recovered;
    }

    public AgeWiseCases setRecovered(ULong recovered) {
        this.recovered = recovered;
        return this;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public AgeWiseCases setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public Timestamp getModifiedAt() {
        return this.modifiedAt;
    }

    public AgeWiseCases setModifiedAt(Timestamp modifiedAt) {
        this.modifiedAt = modifiedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AgeWiseCases (");

        sb.append(id);
        sb.append(", ").append(locationId);
        sb.append(", ").append(age);
        sb.append(", ").append(reportingDate);
        sb.append(", ").append(confirmed);
        sb.append(", ").append(deaths);
        sb.append(", ").append(recovered);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(modifiedAt);

        sb.append(")");
        return sb.toString();
    }
}
