/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cases implements Serializable {

    private static final long serialVersionUID = -1695537697;

    private Integer   id;
    private Integer   locationId;
    private Date      reportingDate;
    private Long      confirmed;
    private Integer   deaths;
    private Long      recovered;
    private Timestamp reportingTimestamp;
    private String    fileName;
    private Timestamp createdAt;
    private Timestamp modifiedAt;

    public Cases() {}

    public Cases(Cases value) {
        this.id = value.id;
        this.locationId = value.locationId;
        this.reportingDate = value.reportingDate;
        this.confirmed = value.confirmed;
        this.deaths = value.deaths;
        this.recovered = value.recovered;
        this.reportingTimestamp = value.reportingTimestamp;
        this.fileName = value.fileName;
        this.createdAt = value.createdAt;
        this.modifiedAt = value.modifiedAt;
    }

    public Cases(
        Integer   id,
        Integer   locationId,
        Date      reportingDate,
        Long      confirmed,
        Integer   deaths,
        Long      recovered,
        Timestamp reportingTimestamp,
        String    fileName,
        Timestamp createdAt,
        Timestamp modifiedAt
    ) {
        this.id = id;
        this.locationId = locationId;
        this.reportingDate = reportingDate;
        this.confirmed = confirmed;
        this.deaths = deaths;
        this.recovered = recovered;
        this.reportingTimestamp = reportingTimestamp;
        this.fileName = fileName;
        this.createdAt = createdAt;
        this.modifiedAt = modifiedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public Cases setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getLocationId() {
        return this.locationId;
    }

    public Cases setLocationId(Integer locationId) {
        this.locationId = locationId;
        return this;
    }

    public Date getReportingDate() {
        return this.reportingDate;
    }

    public Cases setReportingDate(Date reportingDate) {
        this.reportingDate = reportingDate;
        return this;
    }

    public Long getConfirmed() {
        return this.confirmed;
    }

    public Cases setConfirmed(Long confirmed) {
        this.confirmed = confirmed;
        return this;
    }

    public Integer getDeaths() {
        return this.deaths;
    }

    public Cases setDeaths(Integer deaths) {
        this.deaths = deaths;
        return this;
    }

    public Long getRecovered() {
        return this.recovered;
    }

    public Cases setRecovered(Long recovered) {
        this.recovered = recovered;
        return this;
    }

    public Timestamp getReportingTimestamp() {
        return this.reportingTimestamp;
    }

    public Cases setReportingTimestamp(Timestamp reportingTimestamp) {
        this.reportingTimestamp = reportingTimestamp;
        return this;
    }

    public String getFileName() {
        return this.fileName;
    }

    public Cases setFileName(String fileName) {
        this.fileName = fileName;
        return this;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public Cases setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public Timestamp getModifiedAt() {
        return this.modifiedAt;
    }

    public Cases setModifiedAt(Timestamp modifiedAt) {
        this.modifiedAt = modifiedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Cases (");

        sb.append(id);
        sb.append(", ").append(locationId);
        sb.append(", ").append(reportingDate);
        sb.append(", ").append(confirmed);
        sb.append(", ").append(deaths);
        sb.append(", ").append(recovered);
        sb.append(", ").append(reportingTimestamp);
        sb.append(", ").append(fileName);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(modifiedAt);

        sb.append(")");
        return sb.toString();
    }
}
