/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CountryWise implements Serializable {

    private static final long serialVersionUID = 1562023649;

    private Integer id;
    private Date    reportingDate;
    private String  country;
    private Long    confirmed;
    private Integer deaths;
    private Long    recovered;

    public CountryWise() {}

    public CountryWise(CountryWise value) {
        this.id = value.id;
        this.reportingDate = value.reportingDate;
        this.country = value.country;
        this.confirmed = value.confirmed;
        this.deaths = value.deaths;
        this.recovered = value.recovered;
    }

    public CountryWise(
        Integer id,
        Date    reportingDate,
        String  country,
        Long    confirmed,
        Integer deaths,
        Long    recovered
    ) {
        this.id = id;
        this.reportingDate = reportingDate;
        this.country = country;
        this.confirmed = confirmed;
        this.deaths = deaths;
        this.recovered = recovered;
    }

    public Integer getId() {
        return this.id;
    }

    public CountryWise setId(Integer id) {
        this.id = id;
        return this;
    }

    public Date getReportingDate() {
        return this.reportingDate;
    }

    public CountryWise setReportingDate(Date reportingDate) {
        this.reportingDate = reportingDate;
        return this;
    }

    public String getCountry() {
        return this.country;
    }

    public CountryWise setCountry(String country) {
        this.country = country;
        return this;
    }

    public Long getConfirmed() {
        return this.confirmed;
    }

    public CountryWise setConfirmed(Long confirmed) {
        this.confirmed = confirmed;
        return this;
    }

    public Integer getDeaths() {
        return this.deaths;
    }

    public CountryWise setDeaths(Integer deaths) {
        this.deaths = deaths;
        return this;
    }

    public Long getRecovered() {
        return this.recovered;
    }

    public CountryWise setRecovered(Long recovered) {
        this.recovered = recovered;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CountryWise (");

        sb.append(id);
        sb.append(", ").append(reportingDate);
        sb.append(", ").append(country);
        sb.append(", ").append(confirmed);
        sb.append(", ").append(deaths);
        sb.append(", ").append(recovered);

        sb.append(")");
        return sb.toString();
    }
}
