/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Location implements Serializable {

    private static final long serialVersionUID = -572975137;

    private Integer    id;
    private String     country;
    private String     state;
    private BigDecimal latitude;
    private BigDecimal longitude;
    private String     fileName;
    private Timestamp  createdAt;
    private Timestamp  modifiedAt;

    public Location() {}

    public Location(Location value) {
        this.id = value.id;
        this.country = value.country;
        this.state = value.state;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
        this.fileName = value.fileName;
        this.createdAt = value.createdAt;
        this.modifiedAt = value.modifiedAt;
    }

    public Location(
        Integer    id,
        String     country,
        String     state,
        BigDecimal latitude,
        BigDecimal longitude,
        String     fileName,
        Timestamp  createdAt,
        Timestamp  modifiedAt
    ) {
        this.id = id;
        this.country = country;
        this.state = state;
        this.latitude = latitude;
        this.longitude = longitude;
        this.fileName = fileName;
        this.createdAt = createdAt;
        this.modifiedAt = modifiedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public Location setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getCountry() {
        return this.country;
    }

    public Location setCountry(String country) {
        this.country = country;
        return this;
    }

    public String getState() {
        return this.state;
    }

    public Location setState(String state) {
        this.state = state;
        return this;
    }

    public BigDecimal getLatitude() {
        return this.latitude;
    }

    public Location setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
        return this;
    }

    public BigDecimal getLongitude() {
        return this.longitude;
    }

    public Location setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
        return this;
    }

    public String getFileName() {
        return this.fileName;
    }

    public Location setFileName(String fileName) {
        this.fileName = fileName;
        return this;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public Location setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public Timestamp getModifiedAt() {
        return this.modifiedAt;
    }

    public Location setModifiedAt(Timestamp modifiedAt) {
        this.modifiedAt = modifiedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Location (");

        sb.append(id);
        sb.append(", ").append(country);
        sb.append(", ").append(state);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);
        sb.append(", ").append(fileName);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(modifiedAt);

        sb.append(")");
        return sb.toString();
    }
}
