/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Properties implements Serializable {

    private static final long serialVersionUID = -1436144301;

    private UInteger  id;
    private String    key;
    private String    value;
    private Timestamp modifiedAt;

    public Properties() {}

    public Properties(Properties value) {
        this.id = value.id;
        this.key = value.key;
        this.value = value.value;
        this.modifiedAt = value.modifiedAt;
    }

    public Properties(
        UInteger  id,
        String    key,
        String    value,
        Timestamp modifiedAt
    ) {
        this.id = id;
        this.key = key;
        this.value = value;
        this.modifiedAt = modifiedAt;
    }

    public UInteger getId() {
        return this.id;
    }

    public Properties setId(UInteger id) {
        this.id = id;
        return this;
    }

    public String getKey() {
        return this.key;
    }

    public Properties setKey(String key) {
        this.key = key;
        return this;
    }

    public String getValue() {
        return this.value;
    }

    public Properties setValue(String value) {
        this.value = value;
        return this;
    }

    public Timestamp getModifiedAt() {
        return this.modifiedAt;
    }

    public Properties setModifiedAt(Timestamp modifiedAt) {
        this.modifiedAt = modifiedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Properties (");

        sb.append(id);
        sb.append(", ").append(key);
        sb.append(", ").append(value);
        sb.append(", ").append(modifiedAt);

        sb.append(")");
        return sb.toString();
    }
}
