/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.pojos;


import com.corona.insights.jooq.corona_insights.enums.StateWiseSource;

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StateWise implements Serializable {

    private static final long serialVersionUID = -1214466923;

    private UInteger        id;
    private Date            reportingDate;
    private String          country;
    private String          state;
    private Integer         deltaConfirmed;
    private Integer         deltaDeaths;
    private Integer         deltaRecovered;
    private Long            confirmed;
    private Integer         deaths;
    private Long            recovered;
    private Long            active;
    private Integer         deltaActive;
    private StateWiseSource source;
    private Timestamp       createdAt;
    private Timestamp       modifiedAt;

    public StateWise() {}

    public StateWise(StateWise value) {
        this.id = value.id;
        this.reportingDate = value.reportingDate;
        this.country = value.country;
        this.state = value.state;
        this.deltaConfirmed = value.deltaConfirmed;
        this.deltaDeaths = value.deltaDeaths;
        this.deltaRecovered = value.deltaRecovered;
        this.confirmed = value.confirmed;
        this.deaths = value.deaths;
        this.recovered = value.recovered;
        this.active = value.active;
        this.deltaActive = value.deltaActive;
        this.source = value.source;
        this.createdAt = value.createdAt;
        this.modifiedAt = value.modifiedAt;
    }

    public StateWise(
        UInteger        id,
        Date            reportingDate,
        String          country,
        String          state,
        Integer         deltaConfirmed,
        Integer         deltaDeaths,
        Integer         deltaRecovered,
        Long            confirmed,
        Integer         deaths,
        Long            recovered,
        Long            active,
        Integer         deltaActive,
        StateWiseSource source,
        Timestamp       createdAt,
        Timestamp       modifiedAt
    ) {
        this.id = id;
        this.reportingDate = reportingDate;
        this.country = country;
        this.state = state;
        this.deltaConfirmed = deltaConfirmed;
        this.deltaDeaths = deltaDeaths;
        this.deltaRecovered = deltaRecovered;
        this.confirmed = confirmed;
        this.deaths = deaths;
        this.recovered = recovered;
        this.active = active;
        this.deltaActive = deltaActive;
        this.source = source;
        this.createdAt = createdAt;
        this.modifiedAt = modifiedAt;
    }

    public UInteger getId() {
        return this.id;
    }

    public StateWise setId(UInteger id) {
        this.id = id;
        return this;
    }

    public Date getReportingDate() {
        return this.reportingDate;
    }

    public StateWise setReportingDate(Date reportingDate) {
        this.reportingDate = reportingDate;
        return this;
    }

    public String getCountry() {
        return this.country;
    }

    public StateWise setCountry(String country) {
        this.country = country;
        return this;
    }

    public String getState() {
        return this.state;
    }

    public StateWise setState(String state) {
        this.state = state;
        return this;
    }

    public Integer getDeltaConfirmed() {
        return this.deltaConfirmed;
    }

    public StateWise setDeltaConfirmed(Integer deltaConfirmed) {
        this.deltaConfirmed = deltaConfirmed;
        return this;
    }

    public Integer getDeltaDeaths() {
        return this.deltaDeaths;
    }

    public StateWise setDeltaDeaths(Integer deltaDeaths) {
        this.deltaDeaths = deltaDeaths;
        return this;
    }

    public Integer getDeltaRecovered() {
        return this.deltaRecovered;
    }

    public StateWise setDeltaRecovered(Integer deltaRecovered) {
        this.deltaRecovered = deltaRecovered;
        return this;
    }

    public Long getConfirmed() {
        return this.confirmed;
    }

    public StateWise setConfirmed(Long confirmed) {
        this.confirmed = confirmed;
        return this;
    }

    public Integer getDeaths() {
        return this.deaths;
    }

    public StateWise setDeaths(Integer deaths) {
        this.deaths = deaths;
        return this;
    }

    public Long getRecovered() {
        return this.recovered;
    }

    public StateWise setRecovered(Long recovered) {
        this.recovered = recovered;
        return this;
    }

    public Long getActive() {
        return this.active;
    }

    public StateWise setActive(Long active) {
        this.active = active;
        return this;
    }

    public Integer getDeltaActive() {
        return this.deltaActive;
    }

    public StateWise setDeltaActive(Integer deltaActive) {
        this.deltaActive = deltaActive;
        return this;
    }

    public StateWiseSource getSource() {
        return this.source;
    }

    public StateWise setSource(StateWiseSource source) {
        this.source = source;
        return this;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public StateWise setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public Timestamp getModifiedAt() {
        return this.modifiedAt;
    }

    public StateWise setModifiedAt(Timestamp modifiedAt) {
        this.modifiedAt = modifiedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StateWise (");

        sb.append(id);
        sb.append(", ").append(reportingDate);
        sb.append(", ").append(country);
        sb.append(", ").append(state);
        sb.append(", ").append(deltaConfirmed);
        sb.append(", ").append(deltaDeaths);
        sb.append(", ").append(deltaRecovered);
        sb.append(", ").append(confirmed);
        sb.append(", ").append(deaths);
        sb.append(", ").append(recovered);
        sb.append(", ").append(active);
        sb.append(", ").append(deltaActive);
        sb.append(", ").append(source);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(modifiedAt);

        sb.append(")");
        return sb.toString();
    }
}
