/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.daos;


import com.corona.insights.jooq.corona_insights.tables.AgeWiseCases;
import com.corona.insights.jooq.corona_insights.tables.records.AgeWiseCasesRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgeWiseCasesDao extends DAOImpl<AgeWiseCasesRecord, com.corona.insights.jooq.corona_insights.tables.pojos.AgeWiseCases, Integer> {

    /**
     * Create a new AgeWiseCasesDao without any configuration
     */
    public AgeWiseCasesDao() {
        super(AgeWiseCases.AGE_WISE_CASES, com.corona.insights.jooq.corona_insights.tables.pojos.AgeWiseCases.class);
    }

    /**
     * Create a new AgeWiseCasesDao with an attached configuration
     */
    public AgeWiseCasesDao(Configuration configuration) {
        super(AgeWiseCases.AGE_WISE_CASES, com.corona.insights.jooq.corona_insights.tables.pojos.AgeWiseCases.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.corona.insights.jooq.corona_insights.tables.pojos.AgeWiseCases object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.AgeWiseCases> fetchById(Integer... values) {
        return fetch(AgeWiseCases.AGE_WISE_CASES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.corona.insights.jooq.corona_insights.tables.pojos.AgeWiseCases fetchOneById(Integer value) {
        return fetchOne(AgeWiseCases.AGE_WISE_CASES.ID, value);
    }

    /**
     * Fetch records that have <code>location_id IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.AgeWiseCases> fetchByLocationId(Integer... values) {
        return fetch(AgeWiseCases.AGE_WISE_CASES.LOCATION_ID, values);
    }

    /**
     * Fetch records that have <code>age IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.AgeWiseCases> fetchByAge(Integer... values) {
        return fetch(AgeWiseCases.AGE_WISE_CASES.AGE, values);
    }

    /**
     * Fetch records that have <code>reporting_date IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.AgeWiseCases> fetchByReportingDate(Timestamp... values) {
        return fetch(AgeWiseCases.AGE_WISE_CASES.REPORTING_DATE, values);
    }

    /**
     * Fetch records that have <code>confirmed IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.AgeWiseCases> fetchByConfirmed(Long... values) {
        return fetch(AgeWiseCases.AGE_WISE_CASES.CONFIRMED, values);
    }

    /**
     * Fetch records that have <code>deaths IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.AgeWiseCases> fetchByDeaths(ULong... values) {
        return fetch(AgeWiseCases.AGE_WISE_CASES.DEATHS, values);
    }

    /**
     * Fetch records that have <code>recovered IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.AgeWiseCases> fetchByRecovered(ULong... values) {
        return fetch(AgeWiseCases.AGE_WISE_CASES.RECOVERED, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.AgeWiseCases> fetchByCreatedAt(Timestamp... values) {
        return fetch(AgeWiseCases.AGE_WISE_CASES.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>modified_at IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.AgeWiseCases> fetchByModifiedAt(Timestamp... values) {
        return fetch(AgeWiseCases.AGE_WISE_CASES.MODIFIED_AT, values);
    }
}
