/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.daos;


import com.corona.insights.jooq.corona_insights.tables.Cases;
import com.corona.insights.jooq.corona_insights.tables.records.CasesRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CasesDao extends DAOImpl<CasesRecord, com.corona.insights.jooq.corona_insights.tables.pojos.Cases, UInteger> {

    /**
     * Create a new CasesDao without any configuration
     */
    public CasesDao() {
        super(Cases.CASES, com.corona.insights.jooq.corona_insights.tables.pojos.Cases.class);
    }

    /**
     * Create a new CasesDao with an attached configuration
     */
    public CasesDao(Configuration configuration) {
        super(Cases.CASES, com.corona.insights.jooq.corona_insights.tables.pojos.Cases.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.corona.insights.jooq.corona_insights.tables.pojos.Cases object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.Cases> fetchById(UInteger... values) {
        return fetch(Cases.CASES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.corona.insights.jooq.corona_insights.tables.pojos.Cases fetchOneById(UInteger value) {
        return fetchOne(Cases.CASES.ID, value);
    }

    /**
     * Fetch records that have <code>location_id IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.Cases> fetchByLocationId(Integer... values) {
        return fetch(Cases.CASES.LOCATION_ID, values);
    }

    /**
     * Fetch records that have <code>reporting_date IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.Cases> fetchByReportingDate(Date... values) {
        return fetch(Cases.CASES.REPORTING_DATE, values);
    }

    /**
     * Fetch records that have <code>confirmed IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.Cases> fetchByConfirmed(Long... values) {
        return fetch(Cases.CASES.CONFIRMED, values);
    }

    /**
     * Fetch records that have <code>deaths IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.Cases> fetchByDeaths(Integer... values) {
        return fetch(Cases.CASES.DEATHS, values);
    }

    /**
     * Fetch records that have <code>recovered IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.Cases> fetchByRecovered(Long... values) {
        return fetch(Cases.CASES.RECOVERED, values);
    }

    /**
     * Fetch records that have <code>reporting_timestamp IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.Cases> fetchByReportingTimestamp(Timestamp... values) {
        return fetch(Cases.CASES.REPORTING_TIMESTAMP, values);
    }

    /**
     * Fetch records that have <code>file_name IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.Cases> fetchByFileName(String... values) {
        return fetch(Cases.CASES.FILE_NAME, values);
    }

    /**
     * Fetch records that have <code>created_At IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.Cases> fetchByCreatedAt(Timestamp... values) {
        return fetch(Cases.CASES.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>modified_at IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.Cases> fetchByModifiedAt(Timestamp... values) {
        return fetch(Cases.CASES.MODIFIED_AT, values);
    }
}
