/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.daos;


import com.corona.insights.jooq.corona_insights.enums.CountryWiseSource;
import com.corona.insights.jooq.corona_insights.tables.CountryWise;
import com.corona.insights.jooq.corona_insights.tables.records.CountryWiseRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CountryWiseDao extends DAOImpl<CountryWiseRecord, com.corona.insights.jooq.corona_insights.tables.pojos.CountryWise, Integer> {

    /**
     * Create a new CountryWiseDao without any configuration
     */
    public CountryWiseDao() {
        super(CountryWise.COUNTRY_WISE, com.corona.insights.jooq.corona_insights.tables.pojos.CountryWise.class);
    }

    /**
     * Create a new CountryWiseDao with an attached configuration
     */
    public CountryWiseDao(Configuration configuration) {
        super(CountryWise.COUNTRY_WISE, com.corona.insights.jooq.corona_insights.tables.pojos.CountryWise.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.corona.insights.jooq.corona_insights.tables.pojos.CountryWise object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.CountryWise> fetchById(Integer... values) {
        return fetch(CountryWise.COUNTRY_WISE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.corona.insights.jooq.corona_insights.tables.pojos.CountryWise fetchOneById(Integer value) {
        return fetchOne(CountryWise.COUNTRY_WISE.ID, value);
    }

    /**
     * Fetch records that have <code>reporting_date IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.CountryWise> fetchByReportingDate(Date... values) {
        return fetch(CountryWise.COUNTRY_WISE.REPORTING_DATE, values);
    }

    /**
     * Fetch records that have <code>country IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.CountryWise> fetchByCountry(String... values) {
        return fetch(CountryWise.COUNTRY_WISE.COUNTRY, values);
    }

    /**
     * Fetch records that have <code>confirmed IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.CountryWise> fetchByConfirmed(Long... values) {
        return fetch(CountryWise.COUNTRY_WISE.CONFIRMED, values);
    }

    /**
     * Fetch records that have <code>deaths IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.CountryWise> fetchByDeaths(Integer... values) {
        return fetch(CountryWise.COUNTRY_WISE.DEATHS, values);
    }

    /**
     * Fetch records that have <code>recovered IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.CountryWise> fetchByRecovered(Long... values) {
        return fetch(CountryWise.COUNTRY_WISE.RECOVERED, values);
    }

    /**
     * Fetch records that have <code>source IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.CountryWise> fetchBySource(CountryWiseSource... values) {
        return fetch(CountryWise.COUNTRY_WISE.SOURCE, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.CountryWise> fetchByCreatedAt(Timestamp... values) {
        return fetch(CountryWise.COUNTRY_WISE.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>modified_at IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.CountryWise> fetchByModifiedAt(Timestamp... values) {
        return fetch(CountryWise.COUNTRY_WISE.MODIFIED_AT, values);
    }
}
