/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.daos;


import com.corona.insights.jooq.corona_insights.tables.DistrictWise;
import com.corona.insights.jooq.corona_insights.tables.records.DistrictWiseRecord;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DistrictWiseDao extends DAOImpl<DistrictWiseRecord, com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise, UInteger> {

    /**
     * Create a new DistrictWiseDao without any configuration
     */
    public DistrictWiseDao() {
        super(DistrictWise.DISTRICT_WISE, com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise.class);
    }

    /**
     * Create a new DistrictWiseDao with an attached configuration
     */
    public DistrictWiseDao(Configuration configuration) {
        super(DistrictWise.DISTRICT_WISE, com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise> fetchById(UInteger... values) {
        return fetch(DistrictWise.DISTRICT_WISE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise fetchOneById(UInteger value) {
        return fetchOne(DistrictWise.DISTRICT_WISE.ID, value);
    }

    /**
     * Fetch records that have <code>reporting_date IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise> fetchByReportingDate(Date... values) {
        return fetch(DistrictWise.DISTRICT_WISE.REPORTING_DATE, values);
    }

    /**
     * Fetch records that have <code>country IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise> fetchByCountry(String... values) {
        return fetch(DistrictWise.DISTRICT_WISE.COUNTRY, values);
    }

    /**
     * Fetch records that have <code>state IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise> fetchByState(String... values) {
        return fetch(DistrictWise.DISTRICT_WISE.STATE, values);
    }

    /**
     * Fetch records that have <code>district IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise> fetchByDistrict(String... values) {
        return fetch(DistrictWise.DISTRICT_WISE.DISTRICT, values);
    }

    /**
     * Fetch records that have <code>confirmed IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise> fetchByConfirmed(Long... values) {
        return fetch(DistrictWise.DISTRICT_WISE.CONFIRMED, values);
    }

    /**
     * Fetch records that have <code>deaths IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise> fetchByDeaths(Integer... values) {
        return fetch(DistrictWise.DISTRICT_WISE.DEATHS, values);
    }

    /**
     * Fetch records that have <code>recovered IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise> fetchByRecovered(Long... values) {
        return fetch(DistrictWise.DISTRICT_WISE.RECOVERED, values);
    }

    /**
     * Fetch records that have <code>latitude IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise> fetchByLatitude(BigDecimal... values) {
        return fetch(DistrictWise.DISTRICT_WISE.LATITUDE, values);
    }

    /**
     * Fetch records that have <code>longitude IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise> fetchByLongitude(BigDecimal... values) {
        return fetch(DistrictWise.DISTRICT_WISE.LONGITUDE, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise> fetchByCreatedAt(Timestamp... values) {
        return fetch(DistrictWise.DISTRICT_WISE.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>modified_at IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.DistrictWise> fetchByModifiedAt(Timestamp... values) {
        return fetch(DistrictWise.DISTRICT_WISE.MODIFIED_AT, values);
    }
}
