/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.daos;


import com.corona.insights.jooq.corona_insights.tables.Properties;
import com.corona.insights.jooq.corona_insights.tables.records.PropertiesRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PropertiesDao extends DAOImpl<PropertiesRecord, com.corona.insights.jooq.corona_insights.tables.pojos.Properties, UInteger> {

    /**
     * Create a new PropertiesDao without any configuration
     */
    public PropertiesDao() {
        super(Properties.PROPERTIES, com.corona.insights.jooq.corona_insights.tables.pojos.Properties.class);
    }

    /**
     * Create a new PropertiesDao with an attached configuration
     */
    public PropertiesDao(Configuration configuration) {
        super(Properties.PROPERTIES, com.corona.insights.jooq.corona_insights.tables.pojos.Properties.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.corona.insights.jooq.corona_insights.tables.pojos.Properties object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.Properties> fetchById(UInteger... values) {
        return fetch(Properties.PROPERTIES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.corona.insights.jooq.corona_insights.tables.pojos.Properties fetchOneById(UInteger value) {
        return fetchOne(Properties.PROPERTIES.ID, value);
    }

    /**
     * Fetch records that have <code>key IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.Properties> fetchByKey(String... values) {
        return fetch(Properties.PROPERTIES.KEY, values);
    }

    /**
     * Fetch records that have <code>value IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.Properties> fetchByValue(String... values) {
        return fetch(Properties.PROPERTIES.VALUE, values);
    }

    /**
     * Fetch records that have <code>modified_at IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.Properties> fetchByModifiedAt(Timestamp... values) {
        return fetch(Properties.PROPERTIES.MODIFIED_AT, values);
    }
}
