/*
 * This file is generated by jOOQ.
 */
package com.corona.insights.jooq.corona_insights.tables.daos;


import com.corona.insights.jooq.corona_insights.tables.ZipCodeMapping;
import com.corona.insights.jooq.corona_insights.tables.records.ZipCodeMappingRecord;

import java.math.BigDecimal;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ZipCodeMappingDao extends DAOImpl<ZipCodeMappingRecord, com.corona.insights.jooq.corona_insights.tables.pojos.ZipCodeMapping, Integer> {

    /**
     * Create a new ZipCodeMappingDao without any configuration
     */
    public ZipCodeMappingDao() {
        super(ZipCodeMapping.ZIP_CODE_MAPPING, com.corona.insights.jooq.corona_insights.tables.pojos.ZipCodeMapping.class);
    }

    /**
     * Create a new ZipCodeMappingDao with an attached configuration
     */
    public ZipCodeMappingDao(Configuration configuration) {
        super(ZipCodeMapping.ZIP_CODE_MAPPING, com.corona.insights.jooq.corona_insights.tables.pojos.ZipCodeMapping.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.corona.insights.jooq.corona_insights.tables.pojos.ZipCodeMapping object) {
        return object.getZip();
    }

    /**
     * Fetch records that have <code>Zip IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.ZipCodeMapping> fetchByZip(Integer... values) {
        return fetch(ZipCodeMapping.ZIP_CODE_MAPPING.ZIP, values);
    }

    /**
     * Fetch a unique record that has <code>Zip = value</code>
     */
    public com.corona.insights.jooq.corona_insights.tables.pojos.ZipCodeMapping fetchOneByZip(Integer value) {
        return fetchOne(ZipCodeMapping.ZIP_CODE_MAPPING.ZIP, value);
    }

    /**
     * Fetch records that have <code>City IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.ZipCodeMapping> fetchByCity(String... values) {
        return fetch(ZipCodeMapping.ZIP_CODE_MAPPING.CITY, values);
    }

    /**
     * Fetch records that have <code>State IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.ZipCodeMapping> fetchByState(String... values) {
        return fetch(ZipCodeMapping.ZIP_CODE_MAPPING.STATE, values);
    }

    /**
     * Fetch records that have <code>Latitude IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.ZipCodeMapping> fetchByLatitude(BigDecimal... values) {
        return fetch(ZipCodeMapping.ZIP_CODE_MAPPING.LATITUDE, values);
    }

    /**
     * Fetch records that have <code>Longitude IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.ZipCodeMapping> fetchByLongitude(BigDecimal... values) {
        return fetch(ZipCodeMapping.ZIP_CODE_MAPPING.LONGITUDE, values);
    }

    /**
     * Fetch records that have <code>Timezone IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.ZipCodeMapping> fetchByTimezone(Integer... values) {
        return fetch(ZipCodeMapping.ZIP_CODE_MAPPING.TIMEZONE, values);
    }

    /**
     * Fetch records that have <code>Daylight_savings_time_flag IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.ZipCodeMapping> fetchByDaylightSavingsTimeFlag(Boolean... values) {
        return fetch(ZipCodeMapping.ZIP_CODE_MAPPING.DAYLIGHT_SAVINGS_TIME_FLAG, values);
    }

    /**
     * Fetch records that have <code>geopoint IN (values)</code>
     */
    public List<com.corona.insights.jooq.corona_insights.tables.pojos.ZipCodeMapping> fetchByGeopoint(String... values) {
        return fetch(ZipCodeMapping.ZIP_CODE_MAPPING.GEOPOINT, values);
    }
}
