{
 "title": "COVID-19-Visualisation",
 "time": { "from": "2019-12-31T18:30:00.000Z", "to": "now" },
 "panels": [
  { "title": "Confirmed cases by country", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "USA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\", `confirmed` as \"confirmed cases\" from `country_wise` where country=\"US\" and $__timeFilter(`reporting_date`) ORDER BY `reporting_date` desc"
    }
   ]
  },
  {
   "title": "CHINA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\", sum(`confirmed`) as \"confirmed cases\" from `country_wise` where country like \"%china%\" GROUP BY `reporting_date` ORDER BY `reporting_date` desc;"
    }
   ]
  },
  {
   "title": "Italy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\", `confirmed` as \"confirmed cases\" from `country_wise` where country=\"italy\" and $__timeFilter(`reporting_date`) ORDER BY `reporting_date` desc"
    }
   ]
  },
  {
   "title": "India",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\", `confirmed` as \"confirmed cases\" from `country_wise` where country=\"india\" and $__timeFilter(`reporting_date`) ORDER BY `reporting_date` desc"
    }
   ]
  },
  {
   "title": "World",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\", sum(`confirmed`) as \"confirmed cases\" from `country_wise` GROUP BY `reporting_date` ORDER BY `reporting_date` desc;"
    }
   ]
  },
  {
   "title": "Germany",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\", `confirmed` as \"confirmed cases\" from `country_wise` where country=\"germany\" and $__timeFilter(`reporting_date`) ORDER BY `reporting_date` desc"
    }
   ]
  },
  {
   "title": "Iran",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\", `confirmed` as \"confirmed cases\" from `country_wise` where country=\"iran\" and $__timeFilter(`reporting_date`) ORDER BY `reporting_date` desc"
    }
   ]
  },
  {
   "title": "Spain",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\", `confirmed` as \"confirmed cases\" from `country_wise` where country=\"spain\" and $__timeFilter(`reporting_date`) ORDER BY `reporting_date` desc"
    }
   ]
  },
  {
   "title": "France",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\", `confirmed` as \"confirmed cases\" from `country_wise` where country=\"france\" and $__timeFilter(`reporting_date`) ORDER BY `reporting_date` desc"
    }
   ]
  }
 ]
}