{
 "title": "country wise confirmed cases stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "United States",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\", `confirmed` as \"confirmed-cases\" from `country_wise` where country =\"US\" ORDER BY `reporting_date` desc;"
    }
   ]
  },
  {
   "title": "China",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\", sum(`confirmed`) as \"confirmed-cases\" from `country_wise` where country like \"%china%\" GROUP BY `reporting_date` ORDER BY `reporting_date` desc;\n"
    }
   ]
  },
  {
   "title": "Italy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\", `confirmed` as \"confirmed-cases\" from `country_wise` where country =\"italy\" ORDER BY `reporting_date` desc;"
    }
   ]
  },
  {
   "title": "Spain",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\", `confirmed` as \"confirmed-cases\" from `country_wise` where country =\"spain\" ORDER BY `reporting_date` desc;"
    }
   ]
  }
 ]
}