{
 "title": "COVID-19-Death Visualisation",
 "time": { "from": "2019-12-31T18:30:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "USA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\",`deaths` as \"deaths\" from `country_wise` where country =\"US\" ORDER BY `reporting_date` desc;\n"
    }
   ]
  },
  {
   "title": "China",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\", sum(`deaths`) as \"deaths\" from `country_wise` where country like \"%china%\" GROUP BY `reporting_date` ORDER BY `reporting_date` desc;"
    }
   ]
  },
  {
   "title": "Italy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\",`deaths` as \"deaths\" from `country_wise` where country =\"italy\" ORDER BY `reporting_date` desc;"
    }
   ]
  },
  {
   "title": "India",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\",`deaths` as \"deaths\" from `country_wise` where country =\"india\" ORDER BY `reporting_date` desc;"
    }
   ]
  },
  {
   "title": "World",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\", sum(`deaths`) as \"deaths\" from `country_wise` GROUP BY `reporting_date` ORDER BY `reporting_date` desc;"
    }
   ]
  },
  {
   "title": "Spain",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\",`deaths` as \"deaths\" from `country_wise` where country =\"spain\" ORDER BY `reporting_date` desc;"
    }
   ]
  },
  {
   "title": "Iran",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\",`deaths` as \"deaths\" from `country_wise` where country =\"iran\" ORDER BY `reporting_date` desc;"
    }
   ]
  },
  {
   "title": "Germany",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\",`deaths` as \"deaths\" from `country_wise` where country =\"germany\" ORDER BY `reporting_date` desc;"
    }
   ]
  },
  {
   "title": "France",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select `reporting_date` as \"time\",`deaths` as \"deaths\" from `country_wise` where country =\"france\" ORDER BY `reporting_date` desc;"
    }
   ]
  }
 ]
}